# use local env.config.yml for your specific configuration

server:
  port: 1337
  context: ''

log:
  # error
  # warn
  # info
  # http
  # verbose
  # debug
  # silly
  level: error
  override:
    # initial server start
    server: info
    # express server lifecycle
    express: http
